name: Auto Image Spider

on:
  repository_dispatch:
    types: [web_crawl]

jobs:
  run-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Execute Scraper
        # 从 Workers 传来的 payload 获取关键词(keyword)和数量(num)
        run: |
          python main.py "${{ github.event.client_payload.keyword }}" ${{ github.event.client_payload.num }}

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Move to GDrive
        # 移动文件到网盘，文件夹按关键词分类
        run: |
          rclone move ./images "gdrive:/美女图片/网站抓取/${{ github.event.client_payload.keyword }}" --delete-empty-src-dirs
